# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'macos-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- script: npm install
  displayName: 'Install dependencies'
# - task: CocoaPods@0
#   displayName: 'CocoaPods install'
#   inputs:
#     workingDirectory: 'ios'
#     forceRepoUpdate: false
- script: |
    cd ios
    pod --version
    pod repo update
    pod install
  displayName: 'install pods'
- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'Certificates.p12'
    certPwd: '22Uftake'
    keychain: 'temp'
    deleteCert: true
- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'BIHelloWorldRNProv.mobileprovision'
    removeProfile: true
- task: Xcode@5
  displayName: 'XCode build'
  inputs:
    actions: 'build'
    scheme: ''
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: 'ios/HelloWorldRN.xcworkspace'
    xcodeVersion: '12' # Options: 8, 9, 10, 11, 12, default, specifyPath
    packageApp: true
    signingOption: 'manual'
    provisioningProfileName: 'BIHelloWorldRNProv'
    provisioningProfileUuid: '18365c32-373e-4c05-9bfb-12db09a6574a'
    teamId: '$(TEAMID)'

